### ISSUE TITLE
New Suggestion

### ISSUE THREAD

**Issue by Abdalrhman258** [Pieeees/0x#7]
meke the script box is coloring as the code like other excuters 
example :
![image](https://user-images.githubusercontent.com/74150319/221448697-84160765-c953-4db8-b666-95bf48a0fa2d.png)

**Comment by Pieeees** [comment]
done

**Comment by Abdalrhman258** [comment]
> done

nice

**Comment by Pieeees** [comment]
updating it in 5 minutes
